function(GENERATE_GET_NTH_ARG_ARGS MAX_ARG_COUNT RESULT_VARIABLE)
    set(INDEX 0)
    set(RESULT "")
    while(MAX_ARG_COUNT GREATER_EQUAL INDEX)
        string(APPEND RESULT " _${INDEX}, ")
        math(EXPR INDEX "${INDEX}+1")
    endwhile()
    set(${RESULT_VARIABLE} "${RESULT}" PARENT_SCOPE)
endfunction()
