function(GENERATE_CONSTANTS_DEFINES MAX_ARG_COUNT RESULT_VARIABLE)
    set(INDEX 0)
    set(RESULT "")
    while(MAX_ARG_COUNT GREATER_EQUAL INDEX)
        math(EXPR NEXT_INDEX "${INDEX}+1")
        string(APPEND RESULT "#define __STR_ENUM_GENERATE_CONSTANTS${NEXT_INDEX}(enum_name, element, ...) __STR_ENUM_GENERATE_CONSTANT(enum_name, element) __STR_ENUM_GENERATE_CONSTANTS${INDEX}(enum_name, __VA_ARGS__)\n")
        set(INDEX ${NEXT_INDEX})
    endwhile()
    set(${RESULT_VARIABLE} ${RESULT} PARENT_SCOPE)
endfunction()

function(GENERATE_CONSTANTS_OVERLOADS MAX_ARG_COUNT RESULT_VARIABLE)
    set(INDEX ${MAX_ARG_COUNT})
    set(RESULT "")
    while(INDEX GREATER 0)
        string(APPEND RESULT "__STR_ENUM_GENERATE_CONSTANTS${INDEX}")
        if(NOT INDEX EQUAL 1)
            string(APPEND RESULT ", ")
        endif()
        math(EXPR INDEX "${INDEX}-1")
    endwhile()
    set(${RESULT_VARIABLE} ${RESULT} PARENT_SCOPE)
endfunction()
