function(GENERATE_COUNT_ARGS_ARGS MAX_ARG_COUNT RESULT_VARIABLE)
    set(INDEX ${MAX_ARG_COUNT})
    set(RESULT "")
    while(INDEX GREATER 0)
        string(APPEND RESULT " ${INDEX}")
        if(NOT INDEX EQUAL 1)
            string(APPEND RESULT ", ")
        endif()
        math(EXPR INDEX "${INDEX}-1")
    endwhile()
    set(${RESULT_VARIABLE} ${RESULT} PARENT_SCOPE)
endfunction()
